name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy .env file contents
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker image
        run: docker build -t typing-backend:latest .

      - name: Login to local Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Tag Docker image for registry
        run: docker tag typing-backend:latest ${{ secrets.REGISTRY }}/typing-backend:latest

      - name: Push Docker image to registry
        run: docker push ${{ secrets.REGISTRY }}/typing-backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY }}
            docker compose -f /srv/typing-backend/docker-compose.yml down
            docker compose -f /srv/typing-backend/docker-compose.yml pull
            docker compose -f /srv/typing-backend/docker-compose.yml up -d